server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/liuyan?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
    username: root
    password: 123456
  thymeleaf:
    cache: false
mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.start.entity
  mapper-locations: com/start/mapper/**Mapper.xml
  config-location: classpath:mybatis.xml
