server:
  port: 8080
spring:
  application:
    name: ORACLE
  #  datasource:
  #    username: root
  #    password: 123456
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://127.0.0.1:3306/utilAndTest?serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowMultiQueries=true
  datasource:
    username: myuser
    password: oracle123
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
mybatis:
  type-aliases-package: com.test.demo
  mapper-locations: com/test/mapper/**Mapper.xml